### PR TITLE
fix: Table().dialect_options wasn't there

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
@mikepii can you add a py.test unit test for this in a new PR, please?

**Comment by mikepii** [comment]
Frankly, I don't remember what this is, but I'll see what I can do. Are you the new maintainer?

**Comment by graingert** [comment]
@mikepii this is a new project, that will be more actively maintained.

**Comment by bbayles** [comment]
For what it's worth:
* This PR comes from binarydud/redshift_sqlalchemy#23, which describes the motivation
* It gets at the Redshift-specific arguments to `Table()` via the keyword arguments dictionary rather than the `dialect_options` dictionary.
* This is needed when using older versions of SQLAlchemy. Versions prior to 0.9.2 didn't have `dialect_options` ([ref](http://docs.sqlalchemy.org/en/rel_1_0/core/sqlelement.html#sqlalchemy.sql.base.DialectKWArgs.dialect_options))

The requirements listed in the readme suggest SQLAlchemy versions from 0.8 are supported, so this would seem to be a good idea unless dropping support for old versions is in the cards.

A test might confirm the SQL generated with this method correctly includes the Redshift-specific options like `SORTKEY`.

**Comment by graingert** [comment]
Okay, I'll just bump the requirements in setup.py unless anyone turns up that really needs to support versions prior to 0.9.2

**Comment by mikepii** [comment]
That sounds like a good idea

**Pull request closed without merging**
