### PR TITLE
Skip alembic for testing if we do not have it installed

### PR DESCRIPTION
**Pull request by cpcloud**

### CODE REVIEW

**Comment by graingert** [comment]
@jklukas @thisfred @bouk: Thoughts?

**Comment by graingert** [comment]
Personally I'm not in favour of this change as I'd rather just "require" tox for all testing including local testing.

**Comment by cpcloud** [comment]
Tox isn't a simple requirement if you're not using virtualenv

**Comment by jklukas** [comment]
I'm not understanding how `alembic` as a dependency relates to `tox`.

**Comment by graingert** [comment]
@jklukas tox automatically installs py.test, alembic sqlalchemy etc. based on the "tox.ini"

**Comment by bouk** [comment]
also :-1: from me, if you want to run the whole test suite you should include alembic

**Comment by cpcloud** [comment]
It's a single line change here vs. me having to uproot my entire Python installation and environment setup. Do you really feel *that* strongly about it?

**Comment by cpcloud** [comment]
Is alembic an optional dependency?

**Comment by cpcloud** [comment]
If it's that big of a deal then I'll just install alembic. Is there any guarantee that future testing will not in some way depend on tox?

**Comment by bouk** [comment]
@cpcloud it's an optional dependency for running it, not for testing it

**Comment by cpcloud** [comment]
I'd like to continue contributing, but if tox were to become a hard requirement for testing that would be a showstopper for me. The alembic dependency is

**Comment by graingert** [comment]
@cpcloud currently it's the only supported test framework eg: Tox must complete on Travis before any PR will be accepted.

However you're free to verify locally however is easiest for you.

**Pull request closed without merging**
