### PR TITLE
auto start stop redshift

### PR DESCRIPTION
**Pull request by graingert**
* [ ] add extra deps
* [ ] test locally before deploying
* [ ] set the correct redshift server instance name

### CODE REVIEW

**Comment by graingert** [comment]
To be honest I think this should be a beanstalk service that manages this over http because I don't trust travis with our encrypted AWS keys (they are too easy to leak)

**Comment by graingert** [comment]
Actually this would probably be best done with a Heroku webservice to spin up the redshift cluster if it's not already running, and an hourly scheduled job to kill the server if test has run for the last hour.

**Comment by graingert** [comment]
@jklukas I'm going to go ahead write this up as a simple heroku web application.

It would be great if you could email me the AWS credentials


you can encrypt them with: 
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAIAQC1WKXrwDmoqUJoiWZ56U0GQmHDO3SNHy3GhQWTjVFFY5bk5zD7IurdZokXoDXBiW6HDtKHCXIJxNcQSDw0yDQRsAVQiwq5NgryZrQEIeLcQqkbPeImMgos+r1InPh8QKtA/IYL29A2uq8aulRe+26Ao3Ecr4NMjR7zR+67MFYkfVA+ChBJms5KNdSfQGDrL1GzeXUMvZlwbv4nBawvM8Im60CU9P9/m9WU0UFUV02ZRFiO2sHExA+2bJKztci5xZpdCAE2nqRTqKbUfQokggkL2PffSMTAydUy0Yk5YQ25ufAV2B5zg9iiQUKhP7BpW4TjtXX4lz3AmhpvmkSrwrAWDTLxMldVhk0zWlAF4SnVlMSWq0yv47nfDhS0iHHaVwBlTdrsE/H90fKdVS6td4MNAPa4O+Ya+EKdMdQv4QKYIXhgkwEkAHFJ3bgVcPLQENTO5DBJWfgE3sOqBdNzPKjdiu86fO719qdPcEOdknXhojuR3qurnkD4dPM0aS/zAHj3wKQ7dmEBkGBhSWVIEYO86KjjyQDCnq6BQ/jMvnC7LQYvNFUx+4088nTlPGClj2SHWVtdzMPAloyGkO5NZIlIo+Jicr1Z/645lsw32TR2pGEA1q7ihuoetsbteZYxH3JPg8cezdbsfeWWaLYYF0fZxmtnWFAlMSxTNhXssu6svdbMK8vLQWwhJnjmZvTMlBFsTTbBpVMZGko3AfSmJ78bFxvSt9DFGW6lxYGzTr7p5t1Yn0Gucqm1hjC3QRZtKOI1uXEuLKW6mfBvm8IqlU2m++uawCzqFnL6a5p47iWJ9Q0ZHHsLXY9ig2MYYvuA0strkFH9I1hA+82qubbOEpzKYQq9eZUibyqIVJXW8h/KVenNd6bhltIDS9lwFLknDSpbHsKA3uB7bfnYvrKdagJj+5O5gBaY17toS8JS4YnMeqJl/IuSDhzqUR7RyD+hae+D1ZDKqGTYCyq5DHJPKN/xVV4a8X0TWektW56JNvXKFwoQnj+y2rzlxP/xEd4al8QGSxsE+VVxMZsw14KFwsnPfiEmcfBp8r4d3C2SahpL1O/1R3/mGSttCCuNq690+g7hgX9M+6PKOUYB7ZpQj7OwPprUGcKQ19vqMEASDNeBhYtPq05sL7qOL1vYVEyh0A7GErRukLn2eG5BvUDHGizLUg+rhm4ahIDh4hq6QEgmmzKzC+Rq94jqQaKr0bU1TOps8x69ce+1mIySN2coTf+b9rLmRKxjkwA+F2WrgPZfPytUChpzgtcebzrg72E7fX+/CbhmjEqm1PrsZAHCNU3vumT4gh//MswM6sFopvRFbqPXk3aEMDFcD1v3wNSCS5fb/k2qDXu4tEXRJIDs3hlINiEZriNSotpEGaMK7NVbOaZPl0qSBUdzVpqPo77BIs8dXCcc0Ovb2rpTBp3OEt0fdlYlT1YvjHeWURxIxrn/eRj67iu3Hx6342Kk6CoWnyYdlsa0XENEahvvp6CBE6WiZGePfnnIBJ/CeiBlIGVLIut9Coo+MU1GOx0vPsa0kk4JCofJBhoqhVjFZi+iM3012Ud9oG82WpaOqHRcQQac+1S//tRHBrFNii87PJwF2s3QQ+ImrLJKx5i0XV7nNfvOBSYaj31gldoFjiuzeUP5LQYUIT3hsQZcaPIWNs/SFzowBJHzEGggg5zVOSMRak8yaHNusZOUXoiUN9kZRXhEQpFpOo1uIW7dMi5qreGIT1zovvWa/gs11b8dzjlyx32Ez7u4eUY6GWSqDl5BbA8FMfUzVvHAFneXtnlD2I5gw3pA5SgcobFTNbve36AGWafYrmPdsRtI1CmnLJbZPschldEI2vfxWtUv7FoQouC4QODmjcOMeXin+gfqBKRpnCulV8n5vSldMlqKrEfWfVzZZ1r/RhIutvndofJp4znbuqxkm7XtECe9J1KAcNfYtmeE8i4OaXqOAYWeWDYHiFwyZ5rnswtJ2PazsRMIF9zelonkdcGX2xLl6m5mWMP3pDhy8AJEhnAcjQH39yIjjVp/c4i2EE0W+FLyrQB6WPpwrFNc1mmRM2eKzv/bMbVoZJCP2PHDyIKiZaS2d/NTuQwRWhUX6JFwEVdtmwdpA/i61SCBaLGVwxHN/OHB8WIlZ8utXGhIsKSYHtwNXD8DiTDken9xiUVoaIcVqs+pIzm+ARJSHplOW4BWUya6tnhN4iZ8BK65iz0W0WPm6pHVu3DBbb9rlodPynB0q9qdwZ5CaoDT1vAyW1PS4zujzZplDH1ahWUDu+qQAQA4B47k4ui3LkGQaeV9INC4R2mIJkhGRCF4waC0k3MRaZ/WLC1z1zIF8K0Gh9gVa29UsUkAvAsDUqyGW+aaMguezNJlh7ybWZZowjNuQpiQx1p5VFP+IsNKEyg488iXv1jYIhO5zsg/p/DTm6w6KQZKRYPQIhAFrW1IMT55nSgxczUItfSuW2SLldONHNaXCwy//GcNPd1DkO9PnAHVe6NAAUpo/KuD6n9z4uHr2hVQo0WpJbu6xHu4y/M3qIhcFCmfipyUbWzDyX+XrPZaVEn2xM5ebFENmEDfmcda2ZsTy23JTYu4mMBxUFmcCinF4SpUmeXc/PilKMi6GmTpnguaBcgUNPHMCliCcPZB4EKihA/vtMDqfAEtN6ZvQrDQSaVagLuP5IyTQVhN9zk9LwRPYfBZTF8PYvwiNuv8aYRL+825QU68buX2rRmbb693Vw9Z6B5yURPzaQ==
```
https://github.com/graingert.keys using https://github.com/shadowhand/git-encrypt

**Comment by jklukas** [comment]
@graingert - I'm not understanding how to use git-encrypt to encrypt text using your public ssh key. I can GPG-encrypt if you point me to a GPG public key, or give me some more guidance to understand what to do with git-encrypt.

**Comment by graingert** [comment]
Oh woops I meant https://github.com/substack/cipherhub

**Comment by jklukas** [comment]
Email sent to tagrain@gmail.com. Let me know if that fails.

**Comment by jklukas** [comment]
And to be clear, the creds I sent are for a `graingert` user, but the `travis` user has identical privs.

**Comment by graingert** [comment]
That failed, did you use the key:

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAIAQC1WKXrwDmoqUJoiWZ56U0GQmHDO3SNHy3GhQWTjVFFY5bk5zD7IurdZokXoDXBiW6HDtKHCXIJxNcQSDw0yDQRsAVQiwq5NgryZrQEIeLcQqkbPeImMgos+r1InPh8QKtA/IYL29A2uq8aulRe+26Ao3Ecr4NMjR7zR+67MFYkfVA+ChBJms5KNdSfQGDrL1GzeXUMvZlwbv4nBawvM8Im60CU9P9/m9WU0UFUV02ZRFiO2sHExA+2bJKztci5xZpdCAE2nqRTqKbUfQokggkL2PffSMTAydUy0Yk5YQ25ufAV2B5zg9iiQUKhP7BpW4TjtXX4lz3AmhpvmkSrwrAWDTLxMldVhk0zWlAF4SnVlMSWq0yv47nfDhS0iHHaVwBlTdrsE/H90fKdVS6td4MNAPa4O+Ya+EKdMdQv4QKYIXhgkwEkAHFJ3bgVcPLQENTO5DBJWfgE3sOqBdNzPKjdiu86fO719qdPcEOdknXhojuR3qurnkD4dPM0aS/zAHj3wKQ7dmEBkGBhSWVIEYO86KjjyQDCnq6BQ/jMvnC7LQYvNFUx+4088nTlPGClj2SHWVtdzMPAloyGkO5NZIlIo+Jicr1Z/645lsw32TR2pGEA1q7ihuoetsbteZYxH3JPg8cezdbsfeWWaLYYF0fZxmtnWFAlMSxTNhXssu6svdbMK8vLQWwhJnjmZvTMlBFsTTbBpVMZGko3AfSmJ78bFxvSt9DFGW6lxYGzTr7p5t1Yn0Gucqm1hjC3QRZtKOI1uXEuLKW6mfBvm8IqlU2m++uawCzqFnL6a5p47iWJ9Q0ZHHsLXY9ig2MYYvuA0strkFH9I1hA+82qubbOEpzKYQq9eZUibyqIVJXW8h/KVenNd6bhltIDS9lwFLknDSpbHsKA3uB7bfnYvrKdagJj+5O5gBaY17toS8JS4YnMeqJl/IuSDhzqUR7RyD+hae+D1ZDKqGTYCyq5DHJPKN/xVV4a8X0TWektW56JNvXKFwoQnj+y2rzlxP/xEd4al8QGSxsE+VVxMZsw14KFwsnPfiEmcfBp8r4d3C2SahpL1O/1R3/mGSttCCuNq690+g7hgX9M+6PKOUYB7ZpQj7OwPprUGcKQ19vqMEASDNeBhYtPq05sL7qOL1vYVEyh0A7GErRukLn2eG5BvUDHGizLUg+rhm4ahIDh4hq6QEgmmzKzC+Rq94jqQaKr0bU1TOps8x69ce+1mIySN2coTf+b9rLmRKxjkwA+F2WrgPZfPytUChpzgtcebzrg72E7fX+/CbhmjEqm1PrsZAHCNU3vumT4gh//MswM6sFopvRFbqPXk3aEMDFcD1v3wNSCS5fb/k2qDXu4tEXRJIDs3hlINiEZriNSotpEGaMK7NVbOaZPl0qSBUdzVpqPo77BIs8dXCcc0Ovb2rpTBp3OEt0fdlYlT1YvjHeWURxIxrn/eRj67iu3Hx6342Kk6CoWnyYdlsa0XENEahvvp6CBE6WiZGePfnnIBJ/CeiBlIGVLIut9Coo+MU1GOx0vPsa0kk4JCofJBhoqhVjFZi+iM3012Ud9oG82WpaOqHRcQQac+1S//tRHBrFNii87PJwF2s3QQ+ImrLJKx5i0XV7nNfvOBSYaj31gldoFjiuzeUP5LQYUIT3hsQZcaPIWNs/SFzowBJHzEGggg5zVOSMRak8yaHNusZOUXoiUN9kZRXhEQpFpOo1uIW7dMi5qreGIT1zovvWa/gs11b8dzjlyx32Ez7u4eUY6GWSqDl5BbA8FMfUzVvHAFneXtnlD2I5gw3pA5SgcobFTNbve36AGWafYrmPdsRtI1CmnLJbZPschldEI2vfxWtUv7FoQouC4QODmjcOMeXin+gfqBKRpnCulV8n5vSldMlqKrEfWfVzZZ1r/RhIutvndofJp4znbuqxkm7XtECe9J1KAcNfYtmeE8i4OaXqOAYWeWDYHiFwyZ5rnswtJ2PazsRMIF9zelonkdcGX2xLl6m5mWMP3pDhy8AJEhnAcjQH39yIjjVp/c4i2EE0W+FLyrQB6WPpwrFNc1mmRM2eKzv/bMbVoZJCP2PHDyIKiZaS2d/NTuQwRWhUX6JFwEVdtmwdpA/i61SCBaLGVwxHN/OHB8WIlZ8utXGhIsKSYHtwNXD8DiTDken9xiUVoaIcVqs+pIzm+ARJSHplOW4BWUya6tnhN4iZ8BK65iz0W0WPm6pHVu3DBbb9rlodPynB0q9qdwZ5CaoDT1vAyW1PS4zujzZplDH1ahWUDu+qQAQA4B47k4ui3LkGQaeV9INC4R2mIJkhGRCF4waC0k3MRaZ/WLC1z1zIF8K0Gh9gVa29UsUkAvAsDUqyGW+aaMguezNJlh7ybWZZowjNuQpiQx1p5VFP+IsNKEyg488iXv1jYIhO5zsg/p/DTm6w6KQZKRYPQIhAFrW1IMT55nSgxczUItfSuW2SLldONHNaXCwy//GcNPd1DkO9PnAHVe6NAAUpo/KuD6n9z4uHr2hVQo0WpJbu6xHu4y/M3qIhcFCmfipyUbWzDyX+XrPZaVEn2xM5ebFENmEDfmcda2ZsTy23JTYu4mMBxUFmcCinF4SpUmeXc/PilKMi6GmTpnguaBcgUNPHMCliCcPZB4EKihA/vtMDqfAEtN6ZvQrDQSaVagLuP5IyTQVhN9zk9LwRPYfBZTF8PYvwiNuv8aYRL+825QU68buX2rRmbb693Vw9Z6B5yURPzaQ==
```

**Comment by jklukas** [comment]
That's the key I used, but could have been some text mangling issues in adding it. I started over and got a different encrypted result. Check your email again and we'll see if this one works.

**Comment by graingert** [comment]
Try:

```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1

mQINBFXu5+sBEACiE7PKhmmesJRHWdkVxIPBt8R6rz0aEvU+Ko0BsYerKoRY6t5i
NtMxawLLUmbXglas3o4J+56OAMzRORboDHBrBT2HpMJKKCkfcwARHQU8xT7+KL9d
tsLPLRC7bEIXs9oBoej825b4pcXjqKlcPMQrEeOjfj8RutowDJm92ZUfu1CeaRdg
TlyBb7ev883XCt0eJvEm3nfbLKeYYasc03TGmoPPGtLTxweuB0v4pNz6VpVMZ7Rm
NtSYm0JJG2xidYYVhcw1x1HhFqeLW/rfU3aeolCtWSLhZkqlx2MSQaEbFgj0U1ca
rJM85TN6/GD86ddrP6Ogbgz1VQN5I+/eleNYvt8Z779zeV55yibWXjeHxe4qIXLj
xrQ/Q4NFpP1Qkq1NVsGgLcfyl4XSPaxybTfy8OJ5Cgd19s+ZjNFY7uCtSbx+zrSr
rwilI6jaS16X0QkeGriJW9KaXlI850SAJGN6fS3/JNG0gMpkUcrtTKXJscUNygBj
NaEZwm+D4vuqd3vO6rxZPcv5l9dgc9YRx2+otJjh9GfplA9p1iOvppeji7tOBTSj
5mkkPS7y6Q+dS6+gde64j/0v+ruMmBcUOd0PawoMJXOHjjZedfuZ/80WUiZN8uD5
f8S5j6/0ARD9wMy+Vwq8EtFSIQSmtg3kg4fntpZIOq4YnXRj2xV3c4YdxwARAQAB
tD5UaG9tYXMgR3JhaW5nZXIgKG9uZSBBV1Mga2V5IGZyb20gamtsdWthcykgPHRh
Z3JhaW5AZ21haWwuY29tPokCPgQTAQIAKAUCVe7n6wIbAwUJAAFRgAYLCQgHAwIG
FQgCCQoLBBYCAwECHgECF4AACgkQHCT5BHwWHdRAeg//efgeFaxmITAe/pDkPFoC
bbvMkfBEAwqs3KTQ3XjtV8oqQ3zACFGZ1rMVsy2LJG8Idx0XTIpQmaO6ztRf+sdZ
no2GFvcd8bQBDWu0EqRk2Eny66NgU45ktNIEzIrRQhgOdko8XbdvVKZd3Rob4Kh7
Lem/08j+WU7bw96DQTNxlKOm7MpC3sMVO2J2g6c/QiE70a46pAhOFjedHR1k08b7
jpm1eyTvT5qPfak0spKJ5EXITkCE5DHanF7Ua3rcY8X+rWNpm1gc7cGZAOn/IQeR
poGCXD0n6VgjOpV97K730Y/jQaQ7VKqZQ3CD3UcSEXbYByp//q6EE7x86xNwYwM0
OCiOmq3VxNhzEH5UwbNmYW/WN9IuMdj2KIcYG4xI7cfHvLmmP3j1HDj9tLBqjt8P
Mx92JtgjUNea2F92WdONWzkSpGLPWB4FUvf+pifbprJUC+ug+0rin7/TJqQyJUtX
y5aMhnTg7mfcKDgcVRHt/7dhyyLztG6H0gjlyOyaZGQNu9ed7abiYReYCBk+LjTN
nijs27G0gp52kBUT/Yx3TIotMs0JTi9GHuY+jNfACZaEJWBRz9HqKH0pMjwtn8wN
r3JGHY2hYNarjjFPzeTtxxAOvPvjaCZTuBYHSk4fRZvDGGorLf8d8KgPA/b+BGGj
Z8fg6tkRDan5rRgCh4jeYOe5Ag0EVe7n6wEQAOKONetIOoVHklb0eGZZn+VjLFtX
gk9pJRcK5EFSWjtkhTPbqbbFWvuM4zPvquSI0lXWDueyVI4adYI/h+t2lSTuZqqq
o6oXhCskzOkBQ5AKNy1xMSAZU5ZaF33fiop397WgZ7AJO3LrCnjlWKGdwqnT9vGX
OjqVdV639ydqFLM39BMqn/1trCFc6qX1O6XZwMYKIgrRQnhDeuWE3vD0xZnbN9LX
m4eqSZBdovEkyOlsl28i9+m8Pk+hCCPe2zf/LjzOeczgLqjp9xflOCdmCJYITQhN
psK9Ld7/KqxDdH2fb8W5+ExnEWyH3Qk0ktIBB17azSb9no4uTBCYlsOntQDMjv24
9yEtZu/YFSxaAj/bHhU13fYzG9ziPWN6It1iwyV/sGrxuATO6mhnPIJGmFE3vHzO
HUB5ZuLy5JK2MD4CNoyQLHQvx6GZiBhNVRr9sIXq/KWZQ1wDWK/ruF6sDye8u6b8
owDiOGVjvCZpWBFh9+HEesAXHDUhofuKdpERlC1goiK0MBOoL/yTiXQCPLN+pe6R
FmkjgGRzQr8eU090+cfV3UUzKZrdYtoBmWZQ4WrYFKqPmy0o8TFS5b3/3o51TjNk
9Ygq5NT5peppTDUOKq25ijhJfJ9RtcwmPDB+Xqi8tzmNWzJSU2ogDlCmDceeZBgN
i0vkRXROrQMIRMYBABEBAAGJAiUEGAECAA8FAlXu5+sCGwwFCQABUYAACgkQHCT5
BHwWHdQt9Q//T+LXkiw+2Swx2Si+z4w40A4YAULtIU/vkh8d7sq7fw8mVtjWzNAw
Gs3r6V9+lROOEJlSk+K+iCRscCCRQMlropElryaJCjZn94TWhu74Z7n/5KTOldlJ
s/Tq/Bjabx9TGeN+QLyo9OG8DJNo4U3sJ2pWVZTsfRV58aQlTkMn/HWlOkAaEprT
Dq/v/jGZx+V81Q4IcJxWsYzJo6bH1dFfUT7USCioZmQDk4tYI94xy9UGELikIEHB
uUM3VTbxvyNJTcLwcO/vW8AVPHSp5+5izTItFHUkgwmbYijc6phVUtIWEz7W78CB
RD3A9WSCaEp+WzvN4cPFSiqQ0bRuoo/A7RPl/nGMO/tJSW75EzKL69RqQYtiKfji
/Yd3N6VySKqYjpYQPFaUfK1yhq8XH224z52UX1QND1ZG3mJ4dP2BuU2wGtKIRpsm
8MwXIidFd+IegTe80Cc6gj3ICzIknDXzPwWO66PefONl3cNsFhAtPCo/XbLvDbC2
6/gtauAsQ/yaJGdFeFXpUp62c2b6m9AjtIPSc8bGwtr8k+/l8zlUX4ZaKDfxdzYM
Otfcs7eFl9lM//RQ+O3SxAGsJq7TsGPV/M1P4yuMVg5ZbekVuRstAug6ZzVNUNni
aTF8E/qcgQzKuQreMVHCOFdER7Awk1V1Bkms+SPANN1L+233vGV3PM8=
=vMKk
-----END PGP PUBLIC KEY BLOCK-----
```

**Pull request closed without merging**
